// <auto-generated />
using System;
using InfrastructureLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324214414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DomainLayer.Domain.Projects.ProjectBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasDiscriminator<int>("ProjectType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DomainLayer.Domain.Tasks.TaskBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasDiscriminator<int>("TaskType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DomainLayer.Domain.Projects.Holiday", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Projects.ProjectBase");

                    b.Property<double>("HolidayHours")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("DomainLayer.Domain.Projects.Project", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Projects.ProjectBase");

                    b.Property<int>("BudgetHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("DomainLayer.Domain.Projects.SickLeave", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Projects.ProjectBase");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicalCertificateId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MissedHours")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DomainLayer.Domain.Projects.Training", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Projects.ProjectBase");

                    b.Property<string>("CertificationLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("DomainLayer.Domain.Tasks.BugTask", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Tasks.TaskBase");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DomainLayer.Domain.Tasks.FeatureTask", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Tasks.TaskBase");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(0);
                });
#pragma warning restore 612, 618
        }
    }
}
